[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "super-octo-spork"
authors = [{name = "Dominik Fuchs", email = "ev3dom@gmx.de"}]
dynamic = ["version", "description"]
